module.exports = {
  uc: {
    actions: [
      "fell through",
      "was too lazy to defeat",
      "blew his brains out with",
      "ran out of disk space because of",
      "committed",
      "fucking died to",
      "died of",
      "ate",
      "decided to eat",
      "played a game called",
      "dove into",
      "touched",
      "completely fucking obliterated",
      "failed to notice",
      "facepalmed into",
      "broke the fourth wall (ｈｅｌｌｏ ｔｈｅｒｅ， ｕｓｅｒ) and encountered",
      "gave sentience to",
      "pushed",
      "deleted",
      "used a discord bot maker to recreate",
      "was lulled to sleep by",
    ],
    things: [
      "a shit the size of the earth.",
      "their computer.",
      "death.",
      "ur mom hah lmao",
      "themselves.",
      "the 1999 hit single smooth by santana featuring rob thomas of matchbox 20",
      "the milk.",
      "the memes.",
      "RedMikePumpkin’s retinas.",
      "an innovative touchpad supporting easy fingertip navigation through up to 10,000 songs.",
      "the sky.",
      "ass",
      "my nonexistent life",
      "you",
      "something.",
      "a reference to TSP that no one except for 10 people will understand.",
      "penny bot",
      "a medium-large pile of children.",
      "a medium-large pile of chicken.",
      "system32",
      "hot shit",
      "some jelly.",
      "Winston Churchill.",
      "a kmode exception that was not handled",
      "an error parsing an expression; expected identifier, got '}'"
    ]
  },
  c: {
    actions: [
      "fell through",
      "was too lazy to defeat",
      "blew his brains out with",
      "ran out of disk space because of",
      "committed",
      "died of",
      "ate",
      "decided to eat",
      "played a game called",
      "dove into",
      "touched",
      "failed to notice",
      "facepalmed into",
      "gave sentience to",
      "pushed",
      "deleted",
      "used a discord bot maker to recreate",
      "was lulled to sleep by",
    ],
    things: [
      "their computer.",
      "death.",
      "ur mom hah lmao",
      "themselves.",
      "the 1999 hit single smooth by santana featuring rob thomas of matchbox 20",
      "the milk.",
      "the memes.",
      "RedMikePumpkin’s retinas.",
      "an innovative touchpad supporting easy fingertip navigation through up to 10,000 songs.",
      "the sky.",
      "my nonexistent life",
      "you",
      "something.",
      "a medium-large pile of chicken.",
      "system32",
      "some jelly.",
      "Winston Churchill.",
      "a kmode exception that was not handled",
      "an error parsing an expression; expected identifier, got '}'"
    ]
  }
}
